export enum Permission {
  CREATEUSER = 'CREATEUSER',
  GETUSER = 'GETUSER',
  UPDATEUSER = 'UPDATEUSER',
  GETUSERPROFILE = 'GETUSERPROFILE',
  GETUSERSUB = 'GETUSERSUB',
  BILLING_ACCESS = 'BILLING_ACCESS',
  CREDIT_ACCESS = 'CREDIT_ACCESS',
  CATALOG_MANAGE = 'CATALOG_MANAGE',
  CATALOG_READ = 'CATALOG_READ',
}
