export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  USERNAME_ALREADY_TAKEN = 'USERNAME_ALREADY_TAKEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  PRICE_NOT_FOUND = 'PRICE_NOT_FOUND',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  CROSS_TIER_UPGRADE_DENIED = 'CROSS_TIER_UPGRADE_DENIED',
  STRIPE_CUSTOMER_MISSING = 'STRIPE_CUSTOMER_MISSING',

  CREDIT_BALANCE_NOT_FOUND = 'CREDIT_BALANCE_NOT_FOUND',
  INSUFFICIENT_CREDITS = 'INSUFFICIENT_CREDITS',
  ADDON_REQUIRES_PRO = 'ADDON_REQUIRES_PRO',

  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_NAME_ALREADY_EXISTS = 'PRODUCT_NAME_ALREADY_EXISTS',
  EXCHANGE_RATE_UNAVAILABLE = 'EXCHANGE_RATE_UNAVAILABLE',

  INVALID_WEBHOOK_SIGNATURE = 'INVALID_WEBHOOK_SIGNATURE',
  
  STRIPE_API_ERROR = 'STRIPE_API_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
